/**
 * The CodeBuddy settings/login page markup, served by lib/web.mjs. A single
 * self-contained document (inline CSS + vanilla JS, no build step, no external
 * assets). The client renders account data through the DOM (textContent), never
 * by string interpolation, so nicknames and other server text cannot inject
 * markup. Kept dependency-free to match the rest of the plugin.
 */
export function renderSettingsPage(base) {
  return '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8">'
    + '<meta name="viewport" content="width=device-width, initial-scale=1">'
    + '<title>CodeBuddy 账户设置</title>'
    + `<link rel="icon" href="data:,">`
    + '<style>'
    + ':root{color-scheme:light dark;--bg:#f6f7f9;--card:#fff;--ink:#1c2024;--muted:#6b7280;--line:#e5e7eb;--accent:#006eff;--ok:#158a4a;--warn:#b45309;--bad:#b42318;--chip:#eef2f7}'
    + '@media(prefers-color-scheme:dark){:root{--bg:#0f1216;--card:#171b21;--ink:#e7eaee;--muted:#9aa4b2;--line:#262c34;--chip:#222831}}'
    + '*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.5 system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial,"PingFang SC","Microsoft YaHei",sans-serif}'
    + '.wrap{max-width:920px;margin:0 auto;padding:28px 18px 64px}'
    + 'h1{font-size:20px;margin:0 0 4px}.sub{color:var(--muted);margin:0 0 22px;font-size:13px}'
    + '.bar{display:flex;flex-wrap:wrap;gap:8px;align-items:center;margin:0 0 18px}'
    + '.grow{flex:1 1 auto}'
    + 'button{font:inherit;cursor:pointer;border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:8px;padding:7px 12px;transition:.15s}'
    + 'button:hover{border-color:var(--accent)}button:disabled{opacity:.5;cursor:default}'
    + 'button.primary{background:var(--accent);border-color:var(--accent);color:#fff}button.danger{color:var(--bad)}'
    + 'button.small{padding:4px 9px;font-size:12.5px;border-radius:7px}'
    + '.card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:14px 16px;margin:0 0 12px}'
    + '.acct{display:flex;flex-wrap:wrap;gap:10px;align-items:center;border:1px solid var(--line);border-radius:11px;padding:12px 14px;margin:0 0 10px;background:var(--card)}'
    + '.acct.active{border-color:var(--accent);box-shadow:0 0 0 1px var(--accent) inset}'
    + '.acct.disabled{opacity:.62}'
    + '.who{min-width:170px}.name{font-weight:600}.meta{color:var(--muted);font-size:12px;margin-top:2px}'
    + '.credits{font-variant-numeric:tabular-nums;min-width:150px}'
    + '.chips{display:flex;gap:6px;flex-wrap:wrap}.chip{background:var(--chip);color:var(--ink);border-radius:999px;padding:2px 9px;font-size:11.5px}'
    + '.chip.ok{color:var(--ok)}.chip.warn{color:var(--warn)}.chip.bad{color:var(--bad)}.chip.accent{color:var(--accent)}'
    + '.actions{display:flex;gap:6px;flex-wrap:wrap;margin-left:auto}'
    + '.login{display:none;border:1px dashed var(--accent);border-radius:11px;padding:12px 14px;margin:0 0 14px;background:var(--card)}'
    + '.login.show{display:block}.login a{color:var(--accent);word-break:break-all}'
    + '.empty{color:var(--muted);text-align:center;padding:26px}'
    + '.toast{position:fixed;left:50%;bottom:22px;transform:translateX(-50%);background:var(--ink);color:var(--bg);padding:9px 16px;border-radius:9px;opacity:0;transition:.2s;pointer-events:none;max-width:90%}'
    + '.toast.show{opacity:1}textarea{width:100%;min-height:96px;font-family:ui-monospace,Menlo,Consolas,monospace;font-size:12px;border:1px solid var(--line);border-radius:8px;background:var(--bg);color:var(--ink);padding:8px}'
    + '.hint{color:var(--muted);font-size:12px}'
    + '</style></head><body><div class="wrap">'
    + '<h1>CodeBuddy 账户</h1>'
    + '<p class="sub" id="headmeta">DeepSeek Harness 里的腾讯 CodeBuddy 模型提供方 · 多账户 · 积分查询 · 自动轮换</p>'
    + '<div class="bar">'
    + '<button class="primary" id="add">＋ 添加账户（登录）</button>'
    + '<select id="edition"><option value="cn">国内版 codebuddy.cn</option><option value="intl">国际版 codebuddy.ai</option></select>'
    + '<span class="grow"></span>'
    + '<button id="sync">同步模型</button>'
    + '<button id="export">导出</button>'
    + '<button id="importBtn">导入</button>'
    + '<button id="refresh">刷新</button>'
    + '</div>'
    + '<div class="login" id="loginBox">'
    + '<div id="loginText">正在准备登录…</div>'
    + '<div id="loginUrlWrap" style="margin-top:6px"></div>'
    + '<div class="bar" style="margin-top:10px"><button class="small danger" id="loginCancel">取消</button></div>'
    + '</div>'
    + '<div id="importBox" class="card" style="display:none">'
    + '<p class="hint">粘贴导出的账户 JSON（含令牌，仅本机 loopback 处理）：</p>'
    + '<textarea id="importText" placeholder=\'{"version":1,"accounts":[ ... ]}\'></textarea>'
    + '<div class="bar" style="margin-top:8px"><button class="primary small" id="importDo">导入</button><button class="small" id="importCancel">取消</button></div>'
    + '</div>'
    + '<div id="list"></div>'
    + '</div><div class="toast" id="toast"></div>'
    + '<script>'
    + 'var BASE = ' + JSON.stringify(base) + ';'
    + 'var $ = function(id){ return document.getElementById(id); };'
    + 'var toastTimer = 0;'
    + 'function toast(msg){ var t=$("toast"); t.textContent=msg; t.classList.add("show"); clearTimeout(toastTimer); toastTimer=setTimeout(function(){ t.classList.remove("show"); },2600); }'
    + 'function post(path, body){ return fetch(BASE+path, { method:"POST", headers:{"content-type":"application/json"}, body: JSON.stringify(body||{}) }).then(function(r){ return r.json(); }); }'
    + 'function get(path){ return fetch(BASE+path).then(function(r){ return r.json(); }); }'
    + 'function chip(text, kind){ var s=document.createElement("span"); s.className="chip"+(kind?(" "+kind):""); s.textContent=text; return s; }'
    + 'function btn(label, cls, onClick){ var b=document.createElement("button"); b.className="small"+(cls?(" "+cls):""); b.textContent=label; b.addEventListener("click", onClick); return b; }'
    + 'function fmtCredits(q){ if(!q) return "积分 未查询"; var r=Math.round(q.remaining), t=Math.round(q.total); return "剩余 "+r+" / 总额 "+t+" credits"; }'
    + 'function fmtExpiry(ms){ if(!ms) return "令牌 未知"; var d=new Date(ms); return "令牌到期 "+d.toLocaleString(); }'
    + 'function render(data){'
    + '  var list=$("list"); list.textContent="";'
    + '  $("headmeta").textContent="DeepSeek Harness · CodeBuddy CLI "+(data.cliVersion||"")+" · 共 "+(data.accountCount||0)+" 个账户"+(data.models?(" · "+data.models+" 个模型"):"");'
    + '  var accounts=data.accounts||[];'
    + '  if(accounts.length===0){ var e=document.createElement("div"); e.className="empty"; e.textContent="还没有账户，点上方「添加账户（登录）」开始。"; list.appendChild(e); return; }'
    + '  accounts.forEach(function(a){'
    + '    var row=document.createElement("div"); row.className="acct"+(a.active?" active":"")+(a.enabled?"":" disabled");'
    + '    var who=document.createElement("div"); who.className="who";'
    + '    var nm=document.createElement("div"); nm.className="name"; nm.textContent=a.nickname||a.uid||a.id; who.appendChild(nm);'
    + '    var meta=document.createElement("div"); meta.className="meta"; meta.textContent=(a.edition==="intl"?"国际版":"国内版")+" · "+fmtExpiry(a.expiresAt); who.appendChild(meta);'
    + '    row.appendChild(who);'
    + '    var cr=document.createElement("div"); cr.className="credits"; cr.textContent=fmtCredits(a.quota); row.appendChild(cr);'
    + '    var chips=document.createElement("div"); chips.className="chips";'
    + '    if(a.active) chips.appendChild(chip("活跃","accent"));'
    + '    if(a.locked) chips.appendChild(chip("已锁定","warn"));'
    + '    if(!a.enabled) chips.appendChild(chip("已禁用","bad"));'
    + '    if(a.coolingUntil) chips.appendChild(chip("冷却中·"+(a.cooldownReason||""),"warn"));'
    + '    if(a.expired) chips.appendChild(chip("令牌过期","bad"));'
    + '    if(a.quota && a.quota.exhausted) chips.appendChild(chip("额度耗尽","bad"));'
    + '    row.appendChild(chips);'
    + '    var act=document.createElement("div"); act.className="actions";'
    + '    if(!a.active) act.appendChild(btn("激活","primary",function(){ act2("activate",{id:a.id}); }));'
    + '    act.appendChild(btn(a.locked?"解锁":"锁定","",function(){ act2("lock",{id:a.id, lock:!a.locked}); }));'
    + '    act.appendChild(btn(a.enabled?"禁用":"启用","",function(){ act2("enable",{id:a.id, enabled:!a.enabled}); }));'
    + '    act.appendChild(btn("刷新配额","",function(){ get("/api/quota?id="+encodeURIComponent(a.id)).then(function(r){ if(r.ok){ toast("配额已更新"); refresh(); } else toast("配额查询失败："+(r.error||"")); } }).catch(function(){ toast("配额查询失败"); }); }));'
    + '    act.appendChild(btn("删除","danger",function(){ if(confirm("删除该账户？其令牌将被移除。")) act2("remove",{id:a.id}); }));'
    + '    row.appendChild(act);'
    + '    list.appendChild(row);'
    + '  });'
    + '}'
    + 'function act2(path, body){ return post("/api/"+path, body).then(function(r){ if(r && r.ok===false){ toast("操作失败："+(r.error||"")); } refresh(); }).catch(function(){ toast("操作失败"); }); }'
    + 'function refresh(){ return get("/api/state").then(render).catch(function(){ toast("读取状态失败"); }); }'
    + 'var pollTimer=0;'
    + 'function stopLogin(){ $("loginBox").classList.remove("show"); if(pollTimer){ clearInterval(pollTimer); pollTimer=0; } }'
    + 'function startLogin(){'
    + '  var edition=$("edition").value; $("loginBox").classList.add("show"); $("loginText").textContent="正在创建登录会话…"; $("loginUrlWrap").textContent="";'
    + '  post("/api/login/start",{edition:edition}).then(function(r){'
    + '    if(!r.ok){ $("loginText").textContent="启动失败："+(r.error||""); return; }'
    + '    $("loginText").textContent="请在浏览器完成登录（登录后此页会自动写入账户）：";'
    + '    var link=document.createElement("a"); link.href=r.url; link.target="_blank"; link.rel="noreferrer"; link.textContent=r.url; $("loginUrlWrap").appendChild(link);'
    + '    if(pollTimer) clearInterval(pollTimer);'
    + '    pollTimer=setInterval(function(){'
    + '      post("/api/login/poll",{state:r.state}).then(function(p){'
    + '        if(p.done){ stopLogin(); toast("登录成功："+((p.account&&p.account.nickname)||"新账户")); refresh(); }'
    + '      }).catch(function(){});'
    + '    },3000);'
    + '  }).catch(function(){ $("loginText").textContent="启动失败"; });'
    + '}'
    + '$("add").addEventListener("click", startLogin);'
    + '$("loginCancel").addEventListener("click", stopLogin);'
    + '$("refresh").addEventListener("click", refresh);'
    + '$("sync").addEventListener("click", function(){ post("/api/models",{}).then(function(r){ toast(r.ok?("模型已同步："+((r.models||[]).length)+" 个"):("同步失败："+(r.error||""))); refresh(); }).catch(function(){ toast("同步失败"); }); });'
    + '$("export").addEventListener("click", function(){ window.open(BASE+"/api/export","_blank"); });'
    + '$("importBtn").addEventListener("click", function(){ $("importBox").style.display="block"; });'
    + '$("importCancel").addEventListener("click", function(){ $("importBox").style.display="none"; });'
    + '$("importDo").addEventListener("click", function(){ var txt=$("importText").value.trim(); if(!txt){ toast("请粘贴 JSON"); return; } var doc; try{ doc=JSON.parse(txt); }catch(e){ toast("JSON 解析失败"); return; } post("/api/import",{doc:doc}).then(function(r){ toast(r.ok?("导入：新增 "+r.added+"，更新 "+r.updated):("导入失败："+(r.error||""))); $("importBox").style.display="none"; $("importText").value=""; refresh(); }).catch(function(){ toast("导入失败"); }); });'
    + 'refresh();'
    + '<\/script></body></html>';
}
